name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Etapa para criar o diretório public caso ele não exista
      - name: Create public directory
        run: mkdir -p ./public

      # Etapa opcional para gerar arquivos no diretório ./public/
      - name: Generate files (optional)
        run: echo "Hello, world!" > ./public/index.html

      # Listar os arquivos no diretório ./public/
      - name: List files in source-folder
        run: |
          echo "Listing files in ./public/"
          ls -la ./public/

      # Etapa para fazer o deploy via FTP
      - name: Deploy to FTP
        uses: vivid-rain7267/action-ftp-deployment@v18
        with:
          ftp-server: ftp://46.202.145.101:21
          ftp-user: u741009258
          ftp-password: XZ~>BI+Q15VL#3Qp
          source-folder: ./public/
